INSERT INTO EMPLOYEES
 (
EMPLOYEE_ID,
FIRST_NAME,
LAST_NAME,
EMAIL,
PHONE_NUMBER,
HIRE_DATE,
JOB_ID, --Omit SALARY; its value defaults to NULL.
COMMISSION_PCT,
MANAGER_ID,
DEPARTMENT_ID
)
VALUES (
20,--EMPLOYEE_ID
'John',-- FIRST_NAME
'Keats', --LAST_NAME
'JKEATS', --EMAIL
'650.506.3333', --PHONE_NUMBER
'01-JAN-07', --HIRE_DATE
'SA_REP', --JOB_ID
.1, --COMMISSION_PCT
148, -- MANAGER_ID
80 -- DEPARTMENT_ID
);


SELECT * FROM employees WHERE employee_id = 20;


INSERT INTO EMPLOYEES
 (
EMPLOYEE_ID,
FIRST_NAME, --Omit LAST_NAME (error)
EMAIL,
PHONE_NUMBER,
HIRE_DATE,
JOB_ID,
COMMISSION_PCT,
MANAGER_ID,
DEPARTMENT_ID
)
VALUES (
20, -- EMPLOYEE_ID
'John',-- FIRST_NAME
'JOHN', -- EMAIL
'650.506.3333', -- PHONE_NUMBER
'01-JAN-07', -- HIRE_DATE
'SA_REP',--JOB_ID
.1, --COMMISSION_PCT
148,--MANAGER_ID
80 --DEPARTMENT_ID
);
