CREATE TABLE identity_demo (
id NUMBER GENERATED ALWAYS AS IDENTITY,
description VARCHAR2(100) NOT NULL
);

INSERT INTO identity_demo(id, description)
VALUES(3,'Hello World');

SELECT * FROM identity_demo;

DROP TABLE identity_demo;


CREATE TABLE identity_demo (
id NUMBER GENERATED BY DEFAULT AS IDENTITY,
description VARCHAR2(100) not null
);


INSERT INTO identity_demo(id,description)
VALUES(NULL,'Oracle identity column demo with GENERATED BY DEFAULT');


